#!/usr/bin/env node
/**
 * ZeroPack Standalone Executable
 * Zero-Dependency JavaScript Bundler, Minifier & RFC 6455 HMR Dev Server
 * Built exclusively with Node.js Native Core Libraries.
 *
 * Auto-generated by ZeroPack build tools.
 */

import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import http from 'node:http';
import crypto from 'node:crypto';
import { parseArgs } from 'node:util';
import { StringDecoder } from 'node:string_decoder';

// ==========================================
// Module: cli.js
// ==========================================
// -----------------------------------------------------------------------------
// 1. Terminal Logger (Zero-dependency ANSI Color Utility)
// -----------------------------------------------------------------------------
export const colors = {
  reset: (text) => `\x1b[0m${text}\x1b[0m`,
  bold: (text) => `\x1b[1m${text}\x1b[22m`,
  dim: (text) => `\x1b[2m${text}\x1b[22m`,
  italic: (text) => `\x1b[3m${text}\x1b[23m`,
  underline: (text) => `\x1b[4m${text}\x1b[24m`,
  
  // Foreground Colors
  black: (text) => `\x1b[30m${text}\x1b[39m`,
  red: (text) => `\x1b[31m${text}\x1b[39m`,
  green: (text) => `\x1b[32m${text}\x1b[39m`,
  yellow: (text) => `\x1b[33m${text}\x1b[39m`,
  blue: (text) => `\x1b[34m${text}\x1b[39m`,
  magenta: (text) => `\x1b[35m${text}\x1b[39m`,
  cyan: (text) => `\x1b[36m${text}\x1b[39m`,
  white: (text) => `\x1b[37m${text}\x1b[39m`,
  gray: (text) => `\x1b[90m${text}\x1b[39m`,
  
  // Bright colors
  brightRed: (text) => `\x1b[91m${text}\x1b[39m`,
  brightGreen: (text) => `\x1b[92m${text}\x1b[39m`,
  brightYellow: (text) => `\x1b[93m${text}\x1b[39m`,
  brightCyan: (text) => `\x1b[96m${text}\x1b[39m`,
  
  // Background Colors
  bgCyan: (text) => `\x1b[46m\x1b[30m${text}\x1b[39m\x1b[49m`,
  bgGreen: (text) => `\x1b[42m\x1b[30m${text}\x1b[39m\x1b[49m`,
  bgYellow: (text) => `\x1b[43m\x1b[30m${text}\x1b[39m\x1b[49m`,
  bgRed: (text) => `\x1b[41m\x1b[37m${text}\x1b[39m\x1b[49m`
};

export const logger = {
  info: (msg) => console.log(`${colors.cyan(colors.bold('[INFO]'))} ${msg}`),
  success: (msg) => console.log(`${colors.green(colors.bold('[SUCCESS]'))} ${msg}`),
  warn: (msg) => console.warn(`${colors.yellow(colors.bold('[WARN]'))} ${msg}`),
  error: (msg) => console.error(`${colors.red(colors.bold('[ERROR]'))} ${msg}`),
  build: (msg) => console.log(`${colors.magenta(colors.bold('[BUILD]'))} ${msg}`),
  server: (msg) => console.log(`${colors.blue(colors.bold('[SERVER]'))} ${msg}`),
  hmr: (msg) => console.log(`${colors.brightCyan(colors.bold('[HMR]'))} ${msg}`),
  raw: (msg) => console.log(msg)
};

// -----------------------------------------------------------------------------
// 2. Native Environment Loader (Zero-dependency .env reader)
// -----------------------------------------------------------------------------
export function loadEnv(envPath = '.env', baseDir = process.cwd()) {
  const resolvedPath = path.isAbsolute(envPath) ? envPath : path.resolve(baseDir, envPath);
  
  if (!fs.existsSync(resolvedPath)) {
    return { loaded: false, count: 0, path: resolvedPath };
  }

  try {
    const content = fs.readFileSync(resolvedPath, 'utf8');
    const lines = content.split(/\r?\n/);
    let count = 0;

    for (const rawLine of lines) {
      const line = rawLine.trim();
      // Skip empty lines and comment lines
      if (!line || line.startsWith('#')) continue;

      // Handle 'export KEY=VALUE' or 'KEY=VALUE'
      const sanitizedLine = line.startsWith('export ') ? line.slice(7).trim() : line;
      const eqIdx = sanitizedLine.indexOf('=');
      if (eqIdx === -1) continue;

      const key = sanitizedLine.slice(0, eqIdx).trim();
      let value = sanitizedLine.slice(eqIdx + 1).trim();

      if (!key) continue;

      // Unquote value if wrapped with single or double quotes
      if (
        (value.startsWith('"') && value.endsWith('"')) ||
        (value.startsWith("'") && value.endsWith("'"))
      ) {
        value = value.slice(1, -1);
      }

      // Handle inline comment after space and #
      const commentIdx = value.indexOf(' #');
      if (commentIdx !== -1) {
        value = value.slice(0, commentIdx).trim();
      }

      // Do not overwrite existing process.env variables unless needed
      if (process.env[key] === undefined) {
        process.env[key] = value;
        count++;
      }
    }

    return { loaded: true, count, path: resolvedPath };
  } catch (err) {
    logger.warn(`Failed to parse .env file at ${resolvedPath}: ${err.message}`);
    return { loaded: false, count: 0, error: err };
  }
}

// -----------------------------------------------------------------------------
// 3. Terminal Banner & Help Menu
// -----------------------------------------------------------------------------
export function printBanner() {
  const banner = `
${colors.cyan(colors.bold('========================================================================'))}
${colors.brightCyan(colors.bold('   ______                 ____             __   '))}
${colors.brightCyan(colors.bold('  / ____/___  _________  / __ \\____ ______/ /__ '))}
${colors.cyan(colors.bold(' / /_  / __ \\/ ___/ __ \\/ /_/ / __ `/ ___/ //_/ '))}
${colors.cyan(colors.bold('/ __/ / /_/ / /  / /_/ / ____/ /_/ / /__/ ,<    '))}
${colors.blue(colors.bold('/_/    \\____/_/   \\____/_/    \\__,_/\\___/_/|_|   '))}
${colors.gray('  ⚡ 100% Zero-Dependency JS Bundler & RFC 6455 HMR Dev Server')}
${colors.gray('  🛡️ Built exclusively with Node.js Native Core Libraries')}
${colors.cyan(colors.bold('========================================================================'))}
`;
  console.log(banner);
}

export function printHelp() {
  printBanner();
  console.log(`
${colors.bold('USAGE:')}
  ${colors.green('zeropack')} [options]
  ${colors.green('node src/cli.js')} [options]

${colors.bold('OPTIONS:')}
  ${colors.yellow('--entry <path>')}     Entry JavaScript/TypeScript file ${colors.dim('(default: src/index.js)')}
  ${colors.yellow('--out <path>')}       Output bundle path ${colors.dim('(default: dist/bundle.js)')}
  ${colors.yellow('--serve')}            Start native HTTP static dev server & RFC 6455 WebSocket HMR
  ${colors.yellow('--port <number>')}    Port for the dev server ${colors.dim('(default: 3000)')}
  ${colors.yellow('--minify')}           Minify output bundle (removes comments & whitespace)
  ${colors.yellow('--env <path>')}       Custom path to .env file ${colors.dim('(default: .env)')}
  ${colors.yellow('--help, -h')}         Display this help message

${colors.bold('EXAMPLES:')}
  ${colors.dim('# Bundle with minification')}
  ${colors.cyan('zeropack --entry src/index.js --out dist/bundle.js --minify')}

  ${colors.dim('# Start dev server with Live Reload / WebSocket HMR on port 8080')}
  ${colors.cyan('zeropack --entry src/index.js --serve --port 8080')}

  ${colors.dim('# Standalone single-file compiler & verification')}
  ${colors.cyan('npm run build-standalone')}
`);
}

// -----------------------------------------------------------------------------
// 4. Arguments Parser using `node:util.parseArgs`
// -----------------------------------------------------------------------------
export function parseCliArgs(args = process.argv.slice(2)) {
  const options = {
    entry: {
      type: 'string',
      default: 'src/index.js'
    },
    out: {
      type: 'string',
      default: 'dist/bundle.js'
    },
    serve: {
      type: 'boolean',
      default: false
    },
    port: {
      type: 'string',
      default: '3000'
    },
    minify: {
      type: 'boolean',
      default: false
    },
    env: {
      type: 'string',
      default: '.env'
    },
    help: {
      type: 'boolean',
      short: 'h',
      default: false
    }
  };

  try {
    const { values, positionals } = parseArgs({
      args,
      options,
      allowPositionals: true,
      strict: false
    });

    // Support positional entry argument if provided (e.g. `zeropack src/main.js`)
    let entry = values.entry;
    if (positionals.length > 0 && values.entry === 'src/index.js') {
      entry = positionals[0];
    }

    return {
      entry,
      out: values.out,
      serve: Boolean(values.serve),
      port: parseInt(values.port, 10) || 3000,
      minify: Boolean(values.minify),
      env: values.env,
      help: Boolean(values.help),
      positionals
    };
  } catch (err) {
    logger.error(`Argument parsing error: ${err.message}`);
    printHelp();
    process.exit(1);
  }
}

// -----------------------------------------------------------------------------
// 5. CLI Execution Lifecycle
// -----------------------------------------------------------------------------
export async function runCli(args = process.argv.slice(2)) {
  const config = parseCliArgs(args);

  if (config.help) {
    printHelp();
    return;
  }

  printBanner();

  // Load .env automatically
  const envResult = loadEnv(config.env);
  if (envResult.loaded) {
    logger.info(`Loaded ${colors.bold(envResult.count)} environment variables from ${colors.dim(envResult.path)}`);
  }

  // Dynamic import of bundler/server so CLI file can be run independently or concatenated
  
  

  const startTime = performance.now();
  logger.build(`Target Entry: ${colors.cyan(config.entry)}`);
  logger.build(`Output Path:  ${colors.cyan(config.out)}`);
  logger.build(`Minification: ${config.minify ? colors.green('ENABLED') : colors.gray('DISABLED')}`);

  try {
    const graph = buildDependencyGraph(config.entry);
    const result = bundleToFile(graph, config.out, {
      minify: config.minify,
      entryPath: config.entry
    });

    const elapsed = (performance.now() - startTime).toFixed(2);
    logger.success(`Bundle generated in ${colors.bold(elapsed + 'ms')} (${colors.cyan(result.size + ' bytes')}) [${colors.green(result.stats.compressionRatio + ' saved')}]`);
    logger.info(`SHA-256 Hash: ${colors.gray(result.hash)}`);

    if (config.serve) {
      
      await startDevServer({
        port: config.port,
        entry: config.entry,
        out: config.out,
        minify: config.minify,
        rootDir: process.cwd(),
        stats: result.stats
      });
    }
  } catch (error) {
    if (error.name === 'BuildError') {
      logger.error(`Build failed in ${colors.cyan(error.file)}: ${error.message}`);
    } else {
      logger.error(`Build failed: ${error.message}`);
    }
    if (process.env.DEBUG) {
      console.error(error.stack);
    }
    // If the initial build fails, we must exit with 1 regardless of serve mode,
    // because the dev server hasn't been started yet.
    process.exit(1);
  }
}

// ==========================================
// Module: parser.js
// ==========================================
export class BuildError extends Error {
  constructor(message, file) {
    super(message);
    this.name = 'BuildError';
    this.file = file;
  }
}

/**
 * Resolves a module specifier relative to the importing file.
 * Checks for extensions (.js, .mjs, .cjs, .ts, .json) and directory indexes.
 */
export function resolveModulePath(fromFile, specifier, rootDir = process.cwd()) {
  let candidate = '';

  if (specifier.startsWith('.') || specifier.startsWith('/')) {
    candidate = path.resolve(path.dirname(fromFile), specifier);
  } else {
    // Treat bare specifier as relative to root or node_modules-like structure
    candidate = path.resolve(rootDir, specifier);
  }

  // 1. Exact file match
  if (fs.existsSync(candidate) && fs.statSync(candidate).isFile()) {
    return candidate;
  }

  // 2. Try file extensions
  const extensions = ['.js', '.mjs', '.cjs', '.ts', '.jsx', '.tsx', '.json'];
  for (const ext of extensions) {
    const withExt = candidate + ext;
    if (fs.existsSync(withExt) && fs.statSync(withExt).isFile()) {
      return withExt;
    }
  }

  // 3. Try directory index file
  if (fs.existsSync(candidate) && fs.statSync(candidate).isDirectory()) {
    for (const ext of extensions) {
      const indexFile = path.join(candidate, `index${ext}`);
      if (fs.existsSync(indexFile) && fs.statSync(indexFile).isFile()) {
        return indexFile;
      }
    }
  }

  throw new BuildError(`Cannot resolve module '${specifier}' requested by '${fromFile}'`, fromFile);
}

/**
 * Extracts import/require specifiers and transforms ESM syntax into runtime CJS format.
 */
export function transformModuleCode(rawCode, filePath) {
  const dependencies = new Set();
  let output = '';
  const importTempVars = new Map();

  if (filePath.endsWith('.json')) {
    return {
      code: `module.exports = ${rawCode.trim() || '{}'};`,
      dependencies: []
    };
  }

  let i = 0;
  const len = rawCode.length;
  let inSingleQuote = false;
  let inDoubleQuote = false;
  let inTemplateLiteral = false;
  let inRegex = false;
  let isEscaped = false;

  function skipWhitespaceAndComments(index) {
    while (index < len) {
      const char = rawCode[index];
      const nextChar = rawCode[index + 1];
      if (/\s/.test(char)) { index++; continue; }
      if (char === '/' && nextChar === '/') {
        index += 2;
        while (index < len && rawCode[index] !== '\n') index++;
        continue;
      }
      if (char === '/' && nextChar === '*') {
        index += 2;
        while (index < len && !(rawCode[index] === '*' && rawCode[index + 1] === '/')) index++;
        index += 2;
        continue;
      }
      break;
    }
    return index;
  }

  function readWord(index) {
    let word = '';
    while (index < len && /[a-zA-Z_$0-9]/.test(rawCode[index])) {
      word += rawCode[index++];
    }
    return { word, index };
  }

  function readString(index) {
    const quote = rawCode[index++];
    let str = '';
    let esc = false;
    while (index < len) {
      const c = rawCode[index++];
      if (esc) { str += c; esc = false; continue; }
      if (c === '\\') { esc = true; continue; }
      if (c === quote) break;
      str += c;
    }
    return { str, index, quote };
  }

  function parseImport(startI) {
    let idx = startI + 6;
    idx = skipWhitespaceAndComments(idx);
    
    if (rawCode[idx] === '(') {
      idx++;
      idx = skipWhitespaceAndComments(idx);
      if (rawCode[idx] === "'" || rawCode[idx] === '"' || rawCode[idx] === '`') {
        const { str: specifier, index: afterString } = readString(idx);
        idx = skipWhitespaceAndComments(afterString);
        if (rawCode[idx] === ')') {
          idx++;
          dependencies.add(specifier);
          return {
            replacement: `Promise.resolve(require('${specifier}'))`,
            newIndex: idx
          };
        }
      }
      throw new BuildError(`Unsupported dynamic import expression`, filePath);
    }

    let clause = '';
    let specifier = '';
    
    if (rawCode[idx] === "'" || rawCode[idx] === '"') {
      const { str, index: afterStr } = readString(idx);
      specifier = str;
      idx = skipWhitespaceAndComments(afterStr);
      
      const { word } = readWord(idx);
      if (word === 'with' || word === 'assert') {
         idx += word.length;
         idx = skipWhitespaceAndComments(idx);
         if (rawCode[idx] === '{') {
            while (idx < len && rawCode[idx] !== '}') idx++;
            if (rawCode[idx] === '}') idx++;
         }
      }
      if (rawCode[idx] === ';') idx++;
      
      dependencies.add(specifier);
      return {
        replacement: `require('${specifier}')` + (rawCode[idx-1] === ';' ? ';' : ''),
        newIndex: idx
      };
    }

    let tokens = [];
    while (idx < len) {
      idx = skipWhitespaceAndComments(idx);
      const { word } = readWord(idx);
      if (word === 'from') {
        idx += 4;
        break;
      }
      if (word) {
        tokens.push({ type: 'word', value: word });
        idx += word.length;
      } else {
        const c = rawCode[idx];
        tokens.push({ type: 'punct', value: c });
        idx++;
      }
    }

    idx = skipWhitespaceAndComments(idx);
    if (rawCode[idx] === "'" || rawCode[idx] === '"') {
      const { str, index: afterStr } = readString(idx);
      specifier = str;
      idx = skipWhitespaceAndComments(afterStr);
      const { word } = readWord(idx);
      if (word === 'with' || word === 'assert') {
         idx += word.length;
         idx = skipWhitespaceAndComments(idx);
         if (rawCode[idx] === '{') {
            while (idx < len && rawCode[idx] !== '}') idx++;
            if (rawCode[idx] === '}') idx++;
         }
      }
      if (rawCode[idx] === ';') idx++;
    } else {
      throw new BuildError(`Expected string literal after 'from'`, filePath);
    }

    dependencies.add(specifier);

    let defaultName = null;
    let namespaceName = null;
    let namedImports = [];

    let t = 0;
    if (tokens[t] && tokens[t].type === 'word' && tokens[t].value !== 'as') {
      defaultName = tokens[t].value;
      t++;
      if (tokens[t] && tokens[t].value === ',') t++;
    }
    
    if (tokens[t] && tokens[t].value === '*') {
      t++;
      if (tokens[t] && tokens[t].value === 'as') {
        t++;
        namespaceName = tokens[t].value;
        t++;
      }
    } else if (tokens[t] && tokens[t].value === '{') {
      t++;
      while (t < tokens.length && tokens[t].value !== '}') {
        if (tokens[t].value === ',') { t++; continue; }
        const orig = tokens[t].value;
        let alias = orig;
        t++;
        if (tokens[t] && tokens[t].value === 'as') {
          t++;
          alias = tokens[t].value;
          t++;
        }
        namedImports.push({ orig, alias });
      }
    }

    let tempVar = importTempVars.get(specifier);
    let isNew = false;
    if (!tempVar) {
      const specifierHash = crypto.createHash('sha256').update(specifier).digest('hex').slice(0, 8);
      tempVar = `__mod_${specifierHash}`;
      importTempVars.set(specifier, tempVar);
      isNew = true;
    }
    
    let lines = [];
    if (isNew) {
      lines.push(`const ${tempVar} = require('${specifier}');`);
    }
    
    if (namespaceName) {
      lines.push(`const ${namespaceName} = ${tempVar};`);
    }
    if (defaultName) {
      lines.push(`const ${defaultName} = ${tempVar}.default !== undefined ? ${tempVar}.default : ${tempVar};`);
    }
    if (namedImports.length > 0) {
      const renamed = namedImports.map(n => n.orig === n.alias ? n.orig : `${n.orig}: ${n.alias}`).join(', ');
      lines.push(`const { ${renamed} } = ${tempVar};`);
    }
    
    return {
      replacement: lines.join('\n') + (rawCode[idx-1] === ';' ? '' : ''),
      newIndex: idx
    };
  }

  function parseExport(startI) {
    let idx = startI + 6;
    idx = skipWhitespaceAndComments(idx);
    
    let { word } = readWord(idx);
    
    if (word === 'default') {
      idx += 7;
      idx = skipWhitespaceAndComments(idx);
      
      let { word: nextWord } = readWord(idx);
      if (nextWord === 'function' || nextWord === 'class') {
        let peekIdx = skipWhitespaceAndComments(idx + nextWord.length);
        let { word: name } = readWord(peekIdx);
        if (name) {
          if (nextWord === 'function') {
            return {
              replacement: `module.exports.default = ${name};\nfunction ${name}`,
              newIndex: peekIdx + name.length
            };
          } else {
            return {
              replacement: `const ${name} = module.exports.default = class ${name}`,
              newIndex: peekIdx + name.length
            };
          }
        }
        return {
          replacement: `module.exports.default = `,
          newIndex: idx
        };
      }
      
      let exprEnd = idx;
      let braceCount = 0;
      let parenCount = 0;
      let inSq = false;
      let inDq = false;
      let inTl = false;
      let isEsc = false;

      while (exprEnd < len) {
        const c = rawCode[exprEnd];
        const nextC = rawCode[exprEnd + 1];
        
        if (isEsc) { isEsc = false; exprEnd++; continue; }
        if (c === '\\') { isEsc = true; exprEnd++; continue; }
        
        if (c === "'" && !inDq && !inTl) { inSq = !inSq; exprEnd++; continue; }
        if (c === '"' && !inSq && !inTl) { inDq = !inDq; exprEnd++; continue; }
        if (c === '`' && !inSq && !inDq) { inTl = !inTl; exprEnd++; continue; }
        if (inSq || inDq || inTl) { exprEnd++; continue; }
        
        if (c === '/' && nextC === '/') {
           exprEnd += 2;
           while (exprEnd < len && rawCode[exprEnd] !== '\n') exprEnd++;
           continue;
        }
        if (c === '/' && nextC === '*') {
           exprEnd += 2;
           while (exprEnd < len && !(rawCode[exprEnd] === '*' && rawCode[exprEnd+1] === '/')) exprEnd++;
           exprEnd += 2;
           continue;
        }
        
        if (c === '{') braceCount++;
        else if (c === '}') braceCount--;
        else if (c === '(') parenCount++;
        else if (c === ')') parenCount--;
        
        if (c === ';' && braceCount === 0 && parenCount === 0) {
          exprEnd++;
          break;
        }
        if (c === '\n' && braceCount === 0 && parenCount === 0) {
          break;
        }
        exprEnd++;
      }
      const expr = rawCode.slice(idx, rawCode[exprEnd - 1] === ';' ? exprEnd - 1 : exprEnd).trim();
      return {
        replacement: `const __defaultExport = (${expr});\nmodule.exports.default = __defaultExport;\nif (typeof __defaultExport === 'object' && __defaultExport !== null) { Object.assign(module.exports, __defaultExport); }\n`,
        newIndex: exprEnd
      };
    }
    
    if (word === 'const' || word === 'let' || word === 'var') {
      idx += word.length;
      idx = skipWhitespaceAndComments(idx);
      const { word: varName } = readWord(idx);
      while (idx < len && rawCode[idx] !== '=') idx++;
      if (rawCode[idx] === '=') idx++;
      return {
        replacement: `${word} ${varName} = module.exports.${varName} =`,
        newIndex: idx
      };
    }
    
    if (word === 'function' || word === 'class') {
      idx += word.length;
      idx = skipWhitespaceAndComments(idx);
      const { word: name } = readWord(idx);
      if (word === 'function') {
        return {
          replacement: `module.exports.${name} = ${name};\nfunction ${name}`,
          newIndex: idx + name.length
        };
      } else {
        return {
          replacement: `const ${name} = module.exports.${name} = class ${name}`,
          newIndex: idx + name.length
        };
      }
    }
    
    if (rawCode[idx] === '{') {
      let tokens = [];
      while (idx < len) {
        idx = skipWhitespaceAndComments(idx);
        const { word: tWord } = readWord(idx);
        if (tWord) {
          tokens.push({ type: 'word', value: tWord });
          idx += tWord.length;
        } else {
          const c = rawCode[idx];
          tokens.push({ type: 'punct', value: c });
          idx++;
          if (c === '}') break;
        }
      }
      
      idx = skipWhitespaceAndComments(idx);
      let { word: fromWord } = readWord(idx);
      
      let reexports = [];
      let t = 1; 
      while (t < tokens.length && tokens[t].value !== '}') {
        if (tokens[t].value === ',') { t++; continue; }
        const orig = tokens[t].value;
        let alias = orig;
        t++;
        if (tokens[t] && tokens[t].value === 'as') {
          t++;
          alias = tokens[t].value;
          t++;
        }
        reexports.push({ orig, alias });
      }
      
      if (fromWord === 'from') {
        idx += 4;
        idx = skipWhitespaceAndComments(idx);
        if (rawCode[idx] === "'" || rawCode[idx] === '"') {
          const { str: specifier, index: afterStr } = readString(idx);
          idx = afterStr;
          idx = skipWhitespaceAndComments(idx);
          const { word: attrWord } = readWord(idx);
          if (attrWord === 'with' || attrWord === 'assert') {
             idx += attrWord.length;
             idx = skipWhitespaceAndComments(idx);
             if (rawCode[idx] === '{') {
                while (idx < len && rawCode[idx] !== '}') idx++;
                if (rawCode[idx] === '}') idx++;
             }
          }
          if (rawCode[idx] === ';') idx++;
          
          dependencies.add(specifier);
          let lines = [];
          for (const { orig, alias } of reexports) {
            lines.push(`module.exports.${alias} = require('${specifier}').${orig};`);
          }
          return {
            replacement: lines.join('\n') + (lines.length > 0 ? '\n' : ''),
            newIndex: idx
          };
        }
      } else {
        if (rawCode[idx] === ';') idx++;
        let lines = [];
        for (const { orig, alias } of reexports) {
          lines.push(`module.exports.${alias} = ${orig};`);
        }
        return {
          replacement: lines.join('\n') + (lines.length > 0 ? '\n' : ''),
          newIndex: idx
        };
      }
    }

    if (rawCode[idx] === '*') {
      idx++;
      idx = skipWhitespaceAndComments(idx);
      let { word: fromWord } = readWord(idx);
      if (fromWord === 'from') {
        idx += 4;
        idx = skipWhitespaceAndComments(idx);
        if (rawCode[idx] === "'" || rawCode[idx] === '"') {
          const { str: specifier, index: afterStr } = readString(idx);
          idx = afterStr;
          idx = skipWhitespaceAndComments(idx);
          if (rawCode[idx] === ';') idx++;
          
          dependencies.add(specifier);
          return {
            replacement: `Object.assign(module.exports, require('${specifier}'));`,
            newIndex: idx
          };
        }
      }
    }

    throw new BuildError(`Unsupported export syntax`, filePath);
  }

  let lastRegexNonWhitespace = '';

  while (i < len) {
    const char = rawCode[i];
    const nextChar = rawCode[i + 1];
    
    if (isEscaped) {
      output += char;
      isEscaped = false;
      i++;
      continue;
    }
    
    if (char === '\\' && (inSingleQuote || inDoubleQuote || inTemplateLiteral || inRegex)) {
      output += char;
      isEscaped = true;
      i++;
      continue;
    }

    if (char === "'" && !inDoubleQuote && !inTemplateLiteral && !inRegex) {
      inSingleQuote = !inSingleQuote;
      output += char;
      i++;
      continue;
    }
    if (char === '"' && !inSingleQuote && !inTemplateLiteral && !inRegex) {
      inDoubleQuote = !inDoubleQuote;
      output += char;
      i++;
      continue;
    }
    if (char === '\`' && !inSingleQuote && !inDoubleQuote && !inRegex) {
      inTemplateLiteral = !inTemplateLiteral;
      output += char;
      i++;
      continue;
    }
    
    if (inSingleQuote || inDoubleQuote || inTemplateLiteral) {
      output += char;
      i++;
      continue;
    }

    if (char === '/' && nextChar === '/' && !inRegex) {
      output += char + nextChar;
      i += 2;
      while (i < len && rawCode[i] !== '\n') {
        output += rawCode[i];
        i++;
      }
      continue;
    }
    if (char === '/' && nextChar === '*' && !inRegex) {
      output += char + nextChar;
      i += 2;
      while (i < len && !(rawCode[i] === '*' && rawCode[i + 1] === '/')) {
        output += rawCode[i];
        i++;
      }
      if (i < len) {
        output += '*/';
        i += 2;
      }
      continue;
    }

    if (char === '/' && !inRegex) {
      const isRegexStart = /[(,=:[!&|?{};]/.test(lastRegexNonWhitespace) || /\breturn$/.test(output.trim());
      if (isRegexStart) {
        inRegex = true;
        output += char;
        i++;
        continue;
      }
    } else if (char === '/' && inRegex) {
      inRegex = false;
      output += char;
      i++;
      continue;
    }
    if (inRegex) {
      output += char;
      i++;
      continue;
    }

    if (!/\s/.test(char)) {
      lastRegexNonWhitespace = char;
    }

    if (/[a-zA-Z_$]/.test(char)) {
      let prevIdx = i - 1;
      while (prevIdx >= 0 && /\s/.test(rawCode[prevIdx])) prevIdx--;
      const prevChar = prevIdx >= 0 ? rawCode[prevIdx] : '';

      const { word, index: afterWord } = readWord(i);
      if (prevChar === '.') {
         output += word;
         i = afterWord;
         continue;
      }
      if (word === 'require') {
         let rIdx = skipWhitespaceAndComments(afterWord);
         if (rawCode[rIdx] === '(') {
           rIdx++;
           rIdx = skipWhitespaceAndComments(rIdx);
           if (rawCode[rIdx] === "'" || rawCode[rIdx] === '"' || rawCode[rIdx] === '`') {
             const { str: specifier } = readString(rIdx);
             dependencies.add(specifier);
           }
         }
         output += word;
         i = afterWord;
      } else if (word === 'import') {
         const { replacement, newIndex } = parseImport(i);
         output += replacement;
         i = newIndex;
      } else if (word === 'export') {
         const { replacement, newIndex } = parseExport(i);
         output += replacement;
         i = newIndex;
      } else {
         output += word;
         i = afterWord;
      }
      continue;
    }

    output += char;
    i++;
  }

  return {
    code: output,
    dependencies: Array.from(dependencies)
  };
}

/**
 * Builds the complete dependency graph starting from entry file.
 * Returns an array of module node objects.
 */
export function buildDependencyGraph(entryPath, rootDir = process.cwd()) {
  const absoluteEntry = path.isAbsolute(entryPath) ? entryPath : path.resolve(rootDir, entryPath);

  if (!fs.existsSync(absoluteEntry)) {
    throw new BuildError(`Entry file not found: ${absoluteEntry}`, absoluteEntry);
  }

  let nextId = 0;
  const fileToIdMap = new Map();
  const graph = [];
  const visitedFiles = new Set();
  const recursionStack = new Set();

  function createModule(absoluteFilePath) {
    let rawContent;
    try {
      rawContent = fs.readFileSync(absoluteFilePath, 'utf8');
    } catch (err) {
      throw new BuildError(`Failed to read file: ${err.message}`, absoluteFilePath);
    }
    const hash = crypto.createHash('sha256').update(rawContent).digest('hex');
    const { code, dependencies } = transformModuleCode(rawContent, absoluteFilePath);

    const id = nextId++;
    fileToIdMap.set(absoluteFilePath, id);

    const moduleNode = {
      id,
      filePath: absoluteFilePath,
      relativePath: path.relative(rootDir, absoluteFilePath).replace(/\\/g, '/'),
      code,
      dependencies,
      mapping: {},
      hash
    };

    return moduleNode;
  }

  function traverse(absoluteFilePath, parentFile = null) {
    if (recursionStack.has(absoluteFilePath)) {
      logger.warn(`Circular dependency detected: ${colors.yellow(path.relative(rootDir, absoluteFilePath))} (imported by ${colors.gray(parentFile ? path.relative(rootDir, parentFile) : 'root')})`);
      return fileToIdMap.get(absoluteFilePath);
    }

    if (visitedFiles.has(absoluteFilePath)) {
      return fileToIdMap.get(absoluteFilePath);
    }

    visitedFiles.add(absoluteFilePath);
    recursionStack.add(absoluteFilePath);

    const moduleNode = createModule(absoluteFilePath);
    graph.push(moduleNode);

    for (const depSpecifier of moduleNode.dependencies) {
      try {
        const resolvedDepPath = resolveModulePath(absoluteFilePath, depSpecifier, rootDir);
        const childId = traverse(resolvedDepPath, absoluteFilePath);
        moduleNode.mapping[depSpecifier] = childId;
      } catch (err) {
        logger.error(`Module resolution failed for '${depSpecifier}' in '${path.relative(rootDir, absoluteFilePath)}': ${err.message}`);
        if (err.name === 'BuildError') throw err;
        throw new BuildError(`Cannot resolve module '${depSpecifier}' imported from '${path.relative(rootDir, absoluteFilePath)}'`, absoluteFilePath);
      }
    }

    recursionStack.delete(absoluteFilePath);
    return moduleNode.id;
  }

  traverse(absoluteEntry);

  return graph;
}

// ==========================================
// Module: bundler.js
// ==========================================
/**
 * Pure zero-dependency minifier using string scanner and state machine.
 * Correctly preserves strings ('...', "...", `...`), template literals, and regexes
 * while stripping single-line comments, multi-line comments, and extraneous whitespace.
 */
export function minifyCode(code) {
  const decoder = new StringDecoder('utf8');
  const buffer = Buffer.from(code);
  const text = decoder.write(buffer) + decoder.end();

  let output = '';
  let i = 0;
  const len = text.length;

  let inSingleQuote = false;
  let inDoubleQuote = false;
  let inTemplateLiteral = false;
  let inRegex = false;
  let isEscaped = false;

  while (i < len) {
    const char = text[i];
    const nextChar = i + 1 < len ? text[i + 1] : '';

    // Handle escapes inside strings/regexes
    if (isEscaped) {
      output += char;
      isEscaped = false;
      i++;
      continue;
    }

    if (char === '\\' && (inSingleQuote || inDoubleQuote || inTemplateLiteral || inRegex)) {
      output += char;
      isEscaped = true;
      i++;
      continue;
    }

    // Single-quote string literal
    if (char === "'" && !inDoubleQuote && !inTemplateLiteral && !inRegex) {
      inSingleQuote = !inSingleQuote;
      output += char;
      i++;
      continue;
    }

    // Double-quote string literal
    if (char === '"' && !inSingleQuote && !inTemplateLiteral && !inRegex) {
      inDoubleQuote = !inDoubleQuote;
      output += char;
      i++;
      continue;
    }

    // Template literal (backtick)
    if (char === '`' && !inSingleQuote && !inDoubleQuote && !inRegex) {
      inTemplateLiteral = !inTemplateLiteral;
      output += char;
      i++;
      continue;
    }

    // If inside any string literal, keep characters exactly as-is
    if (inSingleQuote || inDoubleQuote || inTemplateLiteral) {
      output += char;
      i++;
      continue;
    }

    // Check for single-line comments //
    if (char === '/' && nextChar === '/' && !inRegex) {
      i += 2;
      while (i < len && text[i] !== '\n' && text[i] !== '\r') {
        i++;
      }
      continue;
    }

    // Check for multi-line comments /* ... */
    if (char === '/' && nextChar === '*' && !inRegex) {
      i += 2;
      while (i < len && !(text[i] === '*' && text[i + 1] === '/')) {
        i++;
      }
      i += 2; // skip */
      continue;
    }

    // Check for Regex literal start (heuristic: preceded by punctuation or keyword)
    if (char === '/' && !inRegex) {
      const prevNonSpace = output.trim().slice(-1);
      const isRegexStart = /[(,=:[!&|?{};]/.test(prevNonSpace) || output.trim().endsWith('return');
      if (isRegexStart) {
        inRegex = true;
        output += char;
        i++;
        continue;
      }
    } else if (char === '/' && inRegex) {
      inRegex = false;
      output += char;
      i++;
      continue;
    }

    if (inRegex) {
      output += char;
      i++;
      continue;
    }

    // Handle whitespace outside strings
    if (/\s/.test(char)) {
      // Collapse multiple whitespace/newlines into a single space or omit if adjacent to operators
      const lastChar = output.slice(-1);
      if (lastChar && !/[()\[\]{},;:+\-*\/=<>!&|%?]/.test(lastChar)) {
        if (!output.endsWith(' ')) {
          output += ' ';
        }
      }
      i++;
      continue;
    }

    // If adding an operator, strip trailing space if safe
    if (/[()\[\]{},;:+\-*\/=<>!&|%?]/.test(char)) {
      if (output.endsWith(' ')) {
        const charBeforeSpace = output.slice(-2, -1);
        // Avoid merging ++ or -- or keyword ambiguities
        if (!(/[+\-]/.test(char) && /[+\-]/.test(charBeforeSpace))) {
          output = output.slice(0, -1);
        }
      }
    }

    output += char;
    i++;
  }

  // Final cleanup of extra empty lines or spaces
  return output.trim();
}

/**
 * Bundles the dependency graph into a deterministic, single-file IIFE bundle
 * and collects rich build metrics for the ZeroPack dashboard.
 */
export function generateBundle(graph, options = {}) {
  const startTime = Date.now();
  const { minify = false, hmr = false } = options;

  // 1. Calculate original size and module metrics
  let originalSize = 0;
  const moduleStats = [];

  for (const mod of graph) {
    const modBytes = Buffer.byteLength(mod.code || '', 'utf8');
    originalSize += modBytes;
    moduleStats.push({
      id: mod.id,
      filePath: mod.relativePath || mod.filePath,
      size: modBytes
    });
  }

  // Sort modules by size descending for dashboard charts
  moduleStats.sort((a, b) => b.size - a.size);

  // 2. Sort modules deterministically by relative path for byte-identical reproducible builds
  const sortedGraph = [...graph].sort((a, b) => a.relativePath.localeCompare(b.relativePath));

  // 3. Build modules mapping string
  let modulesString = '{\n';
  for (const mod of sortedGraph) {
    const mappingJson = JSON.stringify(mod.mapping);
    modulesString += `  ${mod.id}: [\n`;
    modulesString += `    function(require, module, exports) {\n`;
    modulesString += `// [ZeroPack Module: ${mod.relativePath}]\n`;
    modulesString += mod.code + '\n';
    modulesString += `    },\n`;
    modulesString += `    ${mappingJson}\n`;
    modulesString += `  ],\n`;
  }
  modulesString += '}';

  // 4. Runtime bundle template (Zero-dependency custom require runtime)
  let bundleSource = `/**
 * Bundled by ZeroPack (Zero-Dependency Bundler)
 */
(function(modules) {
  // Module cache
  var installedModules = {};

  function __zeropack_require__(moduleId) {
    // Check if module is in cache
    if (installedModules[moduleId]) {
      return installedModules[moduleId].exports;
    }

    // Create a new module and put it into the cache
    var module = installedModules[moduleId] = {
      id: moduleId,
      loaded: false,
      exports: {}
    };

    var fn = modules[moduleId][0];
    var mapping = modules[moduleId][1];

    function localRequire(name) {
      if (mapping[name] === undefined) {
        throw new Error('ZeroPack: Cannot find module \\'' + name + '\\' from module ID ' + moduleId);
      }
      return __zeropack_require__(mapping[name]);
    }

    // Execute the module function
    try {
      fn(localRequire, module, module.exports);
    } catch (e) {
      console.error('[ZeroPack Runtime Error in Module ' + moduleId + ']:', e);
      throw e;
    }

    module.loaded = true;
    return module.exports;
  }

  // Expose require to window/global in dev mode if needed
  if (typeof window !== 'undefined') {
    window.__zeropack_modules__ = modules;
    window.__zeropack_require__ = __zeropack_require__;
  }

  // Load entry module (id: 0)
  return __zeropack_require__(0);
})(${modulesString});
`;

  // 5. Inject HMR Client Runtime if requested
  if (hmr) {
    const hmrClient = `
// --- ZeroPack Native HMR Client Runtime ---
(function() {
  if (typeof window === 'undefined') return;
  var protocol = window.location.protocol === 'https:' ? 'wss:' : 'ws:';
  var host = window.location.host;
  var wsUrl = protocol + '//' + host + '/__zeropack_hmr';

  function connect() {
    var ws = new WebSocket(wsUrl);
    ws.onopen = function() {
      console.log('%c[ZeroPack HMR]%c Connected to native WebSocket server', 'color: #00bcd4; font-weight: bold;', '');
    };
    ws.onmessage = function(event) {
      try {
        var data = JSON.parse(event.data);
        if (data.type === 'reload') {
          console.log('%c[ZeroPack HMR]%c File changed. Live reloading...', 'color: #4caf50; font-weight: bold;', '');
          window.location.reload();
        }
      } catch(e) {
        console.error('[ZeroPack HMR Error]', e);
      }
    };
    ws.onclose = function() {
      console.log('%c[ZeroPack HMR]%c Disconnected. Reconnecting in 1s...', 'color: #ff9800;', '');
      setTimeout(connect, 1000);
    };
  }
  connect();
})();
`;
    bundleSource += hmrClient;
  }

  // 6. Minify if requested
  if (minify) {
    bundleSource = minifyCode(bundleSource);
  }

  const minifiedSize = Buffer.byteLength(bundleSource, 'utf8');
  const buildTimeMs = Math.max(1, Date.now() - startTime);
  const hash = crypto.createHash('sha256').update(bundleSource).digest('hex');

  const stats = {
    moduleCount: graph.length,
    originalSize,
    minifiedSize,
    buildTimeMs,
    compressionRatio: originalSize > 0 ? (((originalSize - minifiedSize) / originalSize) * 100).toFixed(1) + '%' : '0%',
    modules: moduleStats,
    lastBuildTimestamp: new Date().toLocaleTimeString()
  };

  return {
    code: bundleSource,
    size: minifiedSize,
    hash,
    modulesCount: graph.length,
    stats
  };
}

/**
 * Bundles the graph and writes it directly to disk.
 */
export function bundleToFile(graph, outPath, options = {}) {
  const resolvedOut = path.isAbsolute(outPath) ? outPath : path.resolve(process.cwd(), outPath);
  const outDir = path.dirname(resolvedOut);

  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
  }

  const result = generateBundle(graph, options);
  fs.writeFileSync(resolvedOut, result.code, 'utf8');

  return {
    ...result,
    outputPath: resolvedOut
  };
}

// ==========================================
// Module: dashboard.js
// ==========================================
/**
 * ZeroPack Developer Dashboard (100% Zero-Dependency Frontend)
 * Built with native HTML5, modern CSS Grid/Variables, and Vanilla JavaScript.
 */
export const DASHBOARD_HTML = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>ZeroPack Dashboard & Build Metrics</title>
  <style>
    :root {
      --bg: #090d16;
      --card-bg: #111827;
      --card-hover: #172136;
      --border: #1f2937;
      --text-main: #f3f4f6;
      --text-muted: #9ca3af;
      --accent: #38bdf8;
      --accent-glow: rgba(56, 189, 248, 0.15);
      --accent-purple: #818cf8;
      --success: #34d399;
      --warning: #fbbf24;
      --danger: #f87171;
    }

    * {
      box-sizing: border-box;
      margin: 0;
      padding: 0;
    }

    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
      background-color: var(--bg);
      color: var(--text-main);
      line-height: 1.5;
      min-height: 100vh;
      padding: 2rem;
    }

    .container {
      max-width: 1100px;
      margin: 0 auto;
    }

    /* Header */
    header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      padding-bottom: 2rem;
      border-bottom: 1px solid var(--border);
      margin-bottom: 2rem;
    }

    .logo-area {
      display: flex;
      align-items: center;
      gap: 12px;
    }

    .logo-icon {
      font-size: 2rem;
      background: linear-gradient(135deg, #0284c7, #6366f1);
      width: 48px;
      height: 48px;
      display: flex;
      align-items: center;
      justify-content: center;
      border-radius: 12px;
      box-shadow: 0 0 20px rgba(56, 189, 248, 0.3);
    }

    .logo-text h1 {
      font-size: 1.5rem;
      font-weight: 700;
      background: linear-gradient(to right, #38bdf8, #818cf8);
      -webkit-background-clip: text;
      -webkit-text-fill-color: transparent;
      letter-spacing: -0.5px;
    }

    .logo-text p {
      font-size: 0.82rem;
      color: var(--text-muted);
    }

    .header-actions {
      display: flex;
      align-items: center;
      gap: 12px;
    }

    .status-badge {
      display: inline-flex;
      align-items: center;
      gap: 6px;
      background: rgba(52, 211, 153, 0.1);
      color: var(--success);
      border: 1px solid rgba(52, 211, 153, 0.3);
      padding: 6px 14px;
      border-radius: 9999px;
      font-size: 0.8rem;
      font-weight: 600;
      transition: all 0.3s ease;
    }

    .status-dot {
      width: 8px;
      height: 8px;
      border-radius: 50%;
      background: var(--success);
      box-shadow: 0 0 8px var(--success);
    }

    .reload-flash {
      animation: pulse-flash 1s ease-in-out;
    }

    @keyframes pulse-flash {
      0% { transform: scale(1); background: rgba(56, 189, 248, 0.3); color: #fff; }
      50% { transform: scale(1.1); background: rgba(56, 189, 248, 0.8); color: #fff; }
      100% { transform: scale(1); }
    }

    .btn-refresh {
      background: var(--card-bg);
      border: 1px solid var(--border);
      color: var(--text-main);
      padding: 6px 14px;
      border-radius: 8px;
      font-size: 0.85rem;
      font-weight: 600;
      cursor: pointer;
      display: flex;
      align-items: center;
      gap: 6px;
      transition: all 0.2s;
    }

    .btn-refresh:hover {
      background: var(--card-hover);
      border-color: var(--accent);
    }

    /* Metrics Grid */
    .metrics-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));
      gap: 1.25rem;
      margin-bottom: 2rem;
    }

    .metric-card {
      background: var(--card-bg);
      border: 1px solid var(--border);
      border-radius: 12px;
      padding: 1.5rem;
      position: relative;
      overflow: hidden;
      transition: transform 0.2s, border-color 0.2s;
    }

    .metric-card:hover {
      transform: translateY(-2px);
      border-color: var(--accent);
    }

    .metric-card::before {
      content: '';
      position: absolute;
      top: 0;
      left: 0;
      right: 0;
      height: 3px;
      background: linear-gradient(90deg, var(--accent), var(--accent-purple));
    }

    .metric-title {
      font-size: 0.85rem;
      text-transform: uppercase;
      letter-spacing: 0.5px;
      color: var(--text-muted);
      margin-bottom: 0.5rem;
    }

    .metric-value {
      font-size: 2rem;
      font-weight: 700;
      color: var(--text-main);
      display: flex;
      align-items: baseline;
      gap: 6px;
    }

    .metric-subtext {
      font-size: 0.8rem;
      color: var(--text-muted);
      margin-top: 0.5rem;
    }

    /* Chart Section */
    .panel {
      background: var(--card-bg);
      border: 1px solid var(--border);
      border-radius: 12px;
      padding: 1.75rem;
      margin-bottom: 2rem;
    }

    .panel-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 1.5rem;
    }

    .panel-title {
      font-size: 1.15rem;
      font-weight: 600;
      display: flex;
      align-items: center;
      gap: 8px;
    }

    .bar-chart {
      display: flex;
      flex-direction: column;
      gap: 1rem;
    }

    .bar-item {
      display: flex;
      flex-direction: column;
      gap: 0.35rem;
    }

    .bar-meta {
      display: flex;
      justify-content: space-between;
      font-size: 0.85rem;
    }

    .bar-name {
      font-family: monospace;
      color: var(--text-main);
    }

    .bar-size {
      color: var(--accent);
      font-weight: 600;
    }

    .bar-track {
      background: rgba(255, 255, 255, 0.05);
      border-radius: 6px;
      height: 10px;
      overflow: hidden;
      position: relative;
    }

    .bar-fill {
      background: linear-gradient(90deg, #38bdf8, #818cf8);
      height: 100%;
      border-radius: 6px;
      transition: width 0.6s cubic-bezier(0.4, 0, 0.2, 1);
    }

    /* Footer */
    footer {
      display: flex;
      justify-content: space-between;
      align-items: center;
      color: var(--text-muted);
      font-size: 0.8rem;
      padding-top: 1.5rem;
      border-top: 1px solid var(--border);
    }

    .live-tag {
      background: rgba(56, 189, 248, 0.1);
      color: var(--accent);
      padding: 2px 8px;
      border-radius: 4px;
      font-size: 0.75rem;
      font-family: monospace;
    }
  </style>
</head>
<body>
  <div class="container">
    <header>
      <div class="logo-area">
        <div class="logo-icon">⚡</div>
        <div class="logo-text">
          <h1>ZeroPack Dashboard</h1>
          <p>Zero-Dependency Real-Time Build Metrics & Analytics</p>
        </div>
      </div>
      <div class="header-actions">
        <span id="hmr-badge" class="status-badge">
          <span class="status-dot"></span>
          <span id="hmr-status-text">HMR Live Active</span>
        </span>
        <button id="btn-refresh" class="btn-refresh" onclick="fetchMetrics()">
          <span>🔄</span> Refresh
        </button>
      </div>
    </header>

    <!-- Metrics Cards -->
    <div class="metrics-grid">
      <div class="metric-card">
        <div class="metric-title">Total Modules</div>
        <div class="metric-value" id="val-module-count">--</div>
        <div class="metric-subtext">Scanned & bundled in dependency tree</div>
      </div>

      <div class="metric-card">
        <div class="metric-title">Bundle Size</div>
        <div class="metric-value" id="val-bundle-size">--</div>
        <div class="metric-subtext" id="val-orig-size">Original: -- KB</div>
      </div>

      <div class="metric-card">
        <div class="metric-title">Build Time</div>
        <div class="metric-value" id="val-build-time">-- <span style="font-size: 1rem; color: var(--text-muted);">ms</span></div>
        <div class="metric-subtext" id="val-timestamp">Last build: --</div>
      </div>

      <div class="metric-card">
        <div class="metric-title">Compression Saved</div>
        <div class="metric-value" id="val-compression" style="color: var(--success);">--</div>
        <div class="metric-subtext">Via Native State-Machine Minifier</div>
      </div>
    </div>

    <!-- Largest Modules Chart -->
    <div class="panel">
      <div class="panel-header">
        <div class="panel-title">
          <span>📊</span> Top Module Size Distribution
        </div>
        <span class="live-tag">RFC 6455 STREAM</span>
      </div>
      <div class="bar-chart" id="module-bars">
        <div style="color: var(--text-muted); font-size: 0.9rem;">Loading dependency distribution...</div>
      </div>
    </div>

    <footer>
      <span>ZeroPack v1.0.0 • 100% Native Node.js Toolchain</span>
      <span>Live Endpoint: <code>/__zeropack/stats</code></span>
    </footer>
  </div>

  <script>
    function formatBytes(bytes) {
      if (bytes === 0) return '0 B';
      const k = 1024;
      const sizes = ['B', 'KB', 'MB'];
      const i = Math.floor(Math.log(bytes) / Math.log(k));
      return (bytes / Math.pow(k, i)).toFixed(2) + ' ' + sizes[i];
    }

    async function fetchMetrics() {
      try {
        const res = await fetch('/__zeropack/stats');
        if (!res.ok) return;
        const data = await res.json();
        renderMetrics(data);
      } catch (err) {
        console.error('[ZeroPack Dashboard Error]', err);
      }
    }

    function renderMetrics(stats) {
      if (!stats) return;

      document.getElementById('val-module-count').textContent = stats.moduleCount || 0;
      document.getElementById('val-bundle-size').textContent = formatBytes(stats.minifiedSize || 0);
      document.getElementById('val-orig-size').textContent = 'Original: ' + formatBytes(stats.originalSize || 0);
      document.getElementById('val-build-time').innerHTML = (stats.buildTimeMs || 0) + ' <span style="font-size: 1rem; color: var(--text-muted);">ms</span>';
      document.getElementById('val-compression').textContent = stats.compressionRatio || '0%';
      document.getElementById('val-timestamp').textContent = 'Last built: ' + (stats.lastBuildTimestamp || 'Just now');

      // Render Top Modules Bar Chart
      const container = document.getElementById('module-bars');
      container.innerHTML = '';

      const modules = stats.modules || [];
      const topModules = modules.slice(0, 6);
      const maxSize = topModules.length > 0 ? topModules[0].size : 1;

      if (topModules.length === 0) {
        container.innerHTML = '<div style="color: var(--text-muted);">No modules found.</div>';
        return;
      }

      for (const mod of topModules) {
        const percentage = Math.max(5, Math.min(100, Math.round((mod.size / maxSize) * 100)));
        const item = document.createElement('div');
        item.className = 'bar-item';
        item.innerHTML = \`
          <div class="bar-meta">
            <span class="bar-name">\${mod.filePath}</span>
            <span class="bar-size">\${formatBytes(mod.size)}</span>
          </div>
          <div class="bar-track">
            <div class="bar-fill" style="width: \${percentage}%;"></div>
          </div>
        \`;
        container.appendChild(item);
      }
    }

    // Connect to WebSocket for Live Metric Updates
    function initWebSocket() {
      const protocol = window.location.protocol === 'https:' ? 'wss:' : 'ws:';
      const wsUrl = protocol + '//' + window.location.host + '/__zeropack_hmr';
      const badge = document.getElementById('hmr-badge');
      const badgeText = document.getElementById('hmr-status-text');

      const ws = new WebSocket(wsUrl);

      ws.onopen = function() {
        badge.style.borderColor = 'rgba(52, 211, 153, 0.3)';
        badge.style.color = 'var(--success)';
        badgeText.textContent = 'HMR Live Active';
      };

      ws.onmessage = function(event) {
        try {
          const data = JSON.parse(event.data);
          if (data.type === 'reload') {
            // Flash badge
            badge.classList.add('reload-flash');
            badgeText.textContent = 'Live Reloaded!';
            setTimeout(() => {
              badge.classList.remove('reload-flash');
              badgeText.textContent = 'HMR Live Active';
            }, 1200);

            // Refresh stats without whole page reload
            fetchMetrics();
          }
        } catch (e) {
          console.error(e);
        }
      };

      ws.onclose = function() {
        badge.style.borderColor = 'rgba(248, 113, 113, 0.3)';
        badge.style.color = 'var(--danger)';
        badgeText.textContent = 'Disconnected';
        setTimeout(initWebSocket, 2000);
      };
    }

    // Initial load
    fetchMetrics();
    initWebSocket();
  </script>
</body>
</html>
`;

// ==========================================
// Module: server.js
// ==========================================
// -----------------------------------------------------------------------------
// 1. Native MIME Type Lookup Table
// -----------------------------------------------------------------------------
export const MIME_TYPES = {
  '.html': 'text/html; charset=utf-8',
  '.htm': 'text/html; charset=utf-8',
  '.js': 'application/javascript; charset=utf-8',
  '.mjs': 'application/javascript; charset=utf-8',
  '.cjs': 'application/javascript; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.gif': 'image/gif',
  '.svg': 'image/svg+xml',
  '.ico': 'image/x-icon',
  '.webp': 'image/webp',
  '.wasm': 'application/wasm',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
  '.ttf': 'font/ttf',
  '.txt': 'text/plain; charset=utf-8',
  '.map': 'application/json; charset=utf-8'
};

export function getMimeType(filePath) {
  const ext = path.extname(filePath).toLowerCase();
  return MIME_TYPES[ext] || 'application/octet-stream';
}

export function isPathInsideRoot(rootDir, candidatePath) {
  const resolvedRoot = path.resolve(rootDir);
  const resolvedCandidate = path.resolve(candidatePath);
  const relative = path.relative(resolvedRoot, resolvedCandidate);
  return relative === '' || (!!relative && !relative.startsWith('..') && !path.isAbsolute(relative));
}

export function resolveStaticFilePath(rootDir, requestPathname) {
  let pathname = requestPathname || '/';
  pathname = pathname.replace(/\\/g, '/');

  if (pathname === '/' || pathname === '') {
    pathname = '/index.html';
  }

  const relativePath = pathname.replace(/^\/+/, '');
  const staticRoots = [rootDir, path.join(rootDir, 'public'), path.join(rootDir, 'dist')];

  for (const staticRoot of staticRoots) {
    const candidatePath = path.resolve(staticRoot, relativePath);
    if (!isPathInsideRoot(staticRoot, candidatePath)) {
      continue;
    }
    if (fs.existsSync(candidatePath) && fs.statSync(candidatePath).isFile()) {
      return candidatePath;
    }
  }

  return null;
}

// -----------------------------------------------------------------------------
// 2. RFC 6455 WebSocket Frame Encoder & Parser
// -----------------------------------------------------------------------------
const WS_MAGIC_STRING = '258EAFA5-E914-47DA-95CA-C5AB0DC85B11';

/**
 * Encodes a text payload into an RFC 6455 WebSocket frame (Server-to-Client unmasked)
 */
export function encodeWebSocketFrame(payload, opcode = 0x1) {
  const payloadBuffer = Buffer.isBuffer(payload) ? payload : Buffer.from(typeof payload === 'string' ? payload : JSON.stringify(payload), 'utf8');
  const payloadLength = payloadBuffer.length;

  let headerBuffer;

  if (payloadLength <= 125) {
    headerBuffer = Buffer.alloc(2);
    headerBuffer[0] = 0x80 | (opcode & 0x0f); // FIN bit = 1, Opcode
    headerBuffer[1] = payloadLength;           // Mask bit = 0
  } else if (payloadLength <= 65535) {
    headerBuffer = Buffer.alloc(4);
    headerBuffer[0] = 0x80 | (opcode & 0x0f);
    headerBuffer[1] = 126;
    headerBuffer.writeUInt16BE(payloadLength, 2);
  } else {
    headerBuffer = Buffer.alloc(10);
    headerBuffer[0] = 0x80 | (opcode & 0x0f);
    headerBuffer[1] = 127;
    headerBuffer.writeBigUInt64BE(BigInt(payloadLength), 2);
  }

  return Buffer.concat([headerBuffer, payloadBuffer]);
}

/**
 * Decodes client-to-server RFC 6455 masked WebSocket frames
 */
export function decodeWebSocketFrame(buffer) {
  if (buffer.length < 2) return null;

  const firstByte = buffer[0];
  const secondByte = buffer[1];

  const fin = (firstByte & 0x80) === 0x80;
  const opcode = firstByte & 0x0f;
  const isMasked = (secondByte & 0x80) === 0x80;
  let payloadLength = secondByte & 0x7f;
  let currentOffset = 2;

  if (payloadLength === 126) {
    if (buffer.length < 4) return null;
    payloadLength = buffer.readUInt16BE(currentOffset);
    currentOffset += 2;
  } else if (payloadLength === 127) {
    if (buffer.length < 10) return null;
    payloadLength = Number(buffer.readBigUInt64BE(currentOffset));
    currentOffset += 8;
  }

  let maskingKey = null;
  if (isMasked) {
    if (buffer.length < currentOffset + 4) return null;
    maskingKey = buffer.subarray(currentOffset, currentOffset + 4);
    currentOffset += 4;
  }

  if (buffer.length < currentOffset + payloadLength) return null;
  const rawPayload = buffer.subarray(currentOffset, currentOffset + payloadLength);
  const unmaskedPayload = Buffer.alloc(payloadLength);

  if (isMasked && maskingKey) {
    for (let i = 0; i < payloadLength; i++) {
      unmaskedPayload[i] = rawPayload[i] ^ maskingKey[i % 4];
    }
  } else {
    rawPayload.copy(unmaskedPayload);
  }

  return {
    fin,
    opcode,
    payload: unmaskedPayload,
    text: unmaskedPayload.toString('utf8'),
    totalFrameLength: currentOffset + payloadLength
  };
}

// -----------------------------------------------------------------------------
// 3. Dev Server & HMR Engine
// -----------------------------------------------------------------------------
export async function startDevServer(options = {}) {
  const {
    port = 3000,
    entry = 'src/index.js',
    out = 'dist/bundle.js',
    minify = false,
    rootDir = process.cwd(),
    host = '127.0.0.1',
    stats: initialStats = null
  } = options;

  let currentStats = initialStats;
  const activeSockets = new Set();

  // Helper to broadcast WebSocket message to all connected clients
  function broadcast(data) {
    const frame = encodeWebSocketFrame(data);
    for (const socket of activeSockets) {
      try {
        if (!socket.destroyed) {
          socket.write(frame);
        }
      } catch (err) {
        activeSockets.delete(socket);
      }
    }
  }

  let isBuilding = false;
  let pendingBuild = false;

  // Initial / Rebuild compilation
  function compile() {
    isBuilding = true;
    try {
      const graph = buildDependencyGraph(entry, rootDir);
      const outputPath = path.isAbsolute(out) ? out : path.join(rootDir, out);
      const result = bundleToFile(graph, outputPath, { minify, hmr: true });
      result.stats.status = 'success';
      currentStats = result.stats;
      logger.hmr(`Rebuilt bundle: ${colors.green(result.size + ' bytes')} (${colors.gray(result.hash.slice(0, 10))})`);
      return result;
    } catch (err) {
      logger.error(`Rebuild error: ${err.message}`);
      if (currentStats) {
        currentStats.status = 'failed';
        currentStats.error = err.message;
      } else {
        currentStats = { status: 'failed', error: err.message };
      }
      return null;
    } finally {
      isBuilding = false;
      if (pendingBuild) {
        pendingBuild = false;
        process.nextTick(() => {
          const success = compile();
          if (success) {
            broadcast({ type: 'reload', file: 'pending-rebuild', timestamp: Date.now() });
            logger.hmr(`Dispatched ${colors.green('RELOAD')} frame to ${colors.bold(activeSockets.size)} client(s)`);
          }
        });
      }
    }
  }

  if (!currentStats) {
    compile();
  }

  // HTTP Server
  const server = http.createServer((req, res) => {
    let pathname;
    try {
      const parsedUrl = new URL(req.url, `http://localhost:${port}`);
      pathname = decodeURIComponent(parsedUrl.pathname);
    } catch (err) {
      res.writeHead(400, { 'Content-Type': 'text/plain; charset=utf-8' });
      res.end('400 Bad Request');
      return;
    }

    // -------------------------------------------------------------------------
    // Route 1: Built-in ZeroPack Dashboard UI (/__zeropack)
    // -------------------------------------------------------------------------
    if (pathname === '/__zeropack' || pathname === '/__zeropack/') {
      res.writeHead(200, {
        'Content-Type': 'text/html; charset=utf-8',
        'Cache-Control': 'no-cache, no-store, must-revalidate'
      });
      res.end(DASHBOARD_HTML);
      return;
    }

    // -------------------------------------------------------------------------
    // Route 2: Built-in ZeroPack Stats API (/__zeropack/stats)
    // -------------------------------------------------------------------------
    if (pathname === '/__zeropack/stats') {
      res.writeHead(200, {
        'Content-Type': 'application/json; charset=utf-8',
        'Access-Control-Allow-Origin': '*',
        'Cache-Control': 'no-cache, no-store, must-revalidate'
      });
      res.end(JSON.stringify(currentStats || {}));
      return;
    }

    const filePath = resolveStaticFilePath(rootDir, pathname);

    // Serve file if exists
    if (filePath) {
      const mimeType = getMimeType(filePath);
      let content = fs.readFileSync(filePath);

      // Auto-inject WebSocket client script into HTML files if not already present
      if (mimeType.startsWith('text/html')) {
        let html = content.toString('utf8');
        if (!html.includes('__zeropack_hmr')) {
          const hmrScript = `
<script>
(function() {
  var protocol = window.location.protocol === 'https:' ? 'wss:' : 'ws:';
  var ws = new WebSocket(protocol + '//' + window.location.host + '/__zeropack_hmr');
  ws.onopen = function() { console.log('[ZeroPack DevServer] Connected to live reload'); };
  ws.onmessage = function(e) {
    var data = JSON.parse(e.data);
    if (data.type === 'reload') {
      console.log('[ZeroPack DevServer] Reloading page...');
      window.location.reload();
    }
  };
})();
</script>`;
          if (html.includes('</body>')) {
            html = html.replace('</body>', `${hmrScript}</body>`);
          } else {
            html += hmrScript;
          }
          content = Buffer.from(html, 'utf8');
        }
      }

      res.writeHead(200, {
        'Content-Type': mimeType,
        'Content-Length': content.length,
        'Access-Control-Allow-Origin': '*',
        'Cache-Control': 'no-cache, no-store, must-revalidate'
      });
      res.end(content);
      return;
    }

    // If request is for an HTML page or root fallback
    const indexHtmlPath = path.join(rootDir, 'index.html');
    const publicIndexHtml = path.join(rootDir, 'public', 'index.html');
    const defaultHtml = fs.existsSync(indexHtmlPath) ? indexHtmlPath : (fs.existsSync(publicIndexHtml) ? publicIndexHtml : null);

    if (defaultHtml && (req.headers.accept || '').includes('text/html')) {
      const html = fs.readFileSync(defaultHtml, 'utf8');
      res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8' });
      res.end(html);
      return;
    }

    res.writeHead(404, { 'Content-Type': 'text/plain' });
    res.end(`404 Not Found: ${pathname}`);
  });

  // RFC 6455 WebSocket Upgrade Handler
  server.on('upgrade', (req, socket, head) => {
    // Check HTTP method and valid URL
    if (req.method !== 'GET') {
      socket.write('HTTP/1.1 405 Method Not Allowed\r\n\r\n');
      socket.destroy();
      return;
    }
    if (req.url !== '/__zeropack_hmr') {
      socket.write('HTTP/1.1 404 Not Found\r\n\r\n');
      socket.destroy();
      return;
    }
    // Check required upgrade headers
    if (!req.headers.upgrade || req.headers.upgrade.toLowerCase() !== 'websocket') {
      socket.write('HTTP/1.1 400 Bad Request\r\n\r\n');
      socket.destroy();
      return;
    }
    const secKey = req.headers['sec-websocket-key'];
    if (!secKey) {
      socket.write('HTTP/1.1 400 Bad Request\r\n\r\n');
      socket.destroy();
      return;
    }

    // RFC 6455 Handshake Acceptance Hash
    const acceptHash = crypto
      .createHash('sha1')
      .update(secKey + WS_MAGIC_STRING)
      .digest('base64');

    const headers = [
      'HTTP/1.1 101 Switching Protocols',
      'Upgrade: websocket',
      'Connection: Upgrade',
      `Sec-WebSocket-Accept: ${acceptHash}`,
      '\r\n'
    ];

    socket.write(headers.join('\r\n'));
    activeSockets.add(socket);

    logger.hmr(`Client connected to HMR WebSocket. Active clients: ${colors.bold(activeSockets.size)}`);

    socket.on('data', (buffer) => {
      try {
        const frame = decodeWebSocketFrame(buffer);
        if (frame) {
          // Ping frame (0x9) -> respond with Pong (0xA)
          if (frame.opcode === 0x9) {
            socket.write(encodeWebSocketFrame(frame.payload, 0xa));
          }
          // Close frame (0x8)
          else if (frame.opcode === 0x8) {
            activeSockets.delete(socket);
            socket.end(encodeWebSocketFrame(Buffer.alloc(0), 0x8));
          }
        }
      } catch (err) {
        // Malformed frame or decoding error -> destroy socket securely
        activeSockets.delete(socket);
        socket.destroy();
      }
    });

    socket.on('close', () => {
      activeSockets.delete(socket);
    });

    socket.on('error', () => {
      activeSockets.delete(socket);
      socket.destroy();
    });
  });

  // Native Watcher with 100ms Debounce using `node:fs.watch`
  let debounceTimer = null;
  const watchDir = path.resolve(rootDir, 'src');
  const publicDir = path.resolve(rootDir, 'public');

  function handleWatchEvent(eventType, filename) {
    if (!filename) return;
    if (filename.endsWith('bundle.js') || filename.includes('node_modules') || filename.startsWith('.')) return;

    if (debounceTimer) {
      clearTimeout(debounceTimer);
    }

    debounceTimer = setTimeout(() => {
      debounceTimer = null;
      if (isBuilding) {
        pendingBuild = true;
        return;
      }
      logger.hmr(`File change detected: ${colors.cyan(filename)}. Rebundling...`);
      const success = compile();
      if (success) {
        broadcast({ type: 'reload', file: filename, timestamp: Date.now() });
        logger.hmr(`Dispatched ${colors.green('RELOAD')} frame to ${colors.bold(activeSockets.size)} client(s)`);
      }
    }, 100);
  }

  const watchers = [];

  function startWatchers() {
    if (fs.existsSync(watchDir)) {
      const w1 = fs.watch(watchDir, { recursive: true }, handleWatchEvent);
      w1.on('error', (err) => logger.warn(`Watcher error on ${watchDir}: ${err.message}`));
      watchers.push(w1);
    }
    if (fs.existsSync(publicDir)) {
      const w2 = fs.watch(publicDir, { recursive: true }, handleWatchEvent);
      w2.on('error', (err) => logger.warn(`Watcher error on ${publicDir}: ${err.message}`));
      watchers.push(w2);
    }
  }

  function closeServer() {
    if (debounceTimer) {
      clearTimeout(debounceTimer);
      debounceTimer = null;
    }
    for (const w of watchers) {
      try { w.close(); } catch(e) {}
    }
    for (const s of activeSockets) {
      try { s.destroy(); } catch(e) {}
    }
    return new Promise((resolve) => server.close(resolve));
  }

  return new Promise((resolve, reject) => {
    server.listen(port, host, () => {
      const address = server.address();
      const actualPort = typeof address === 'object' && address ? address.port : port;
      startWatchers();
      logger.server(`Development server running at: ${colors.green(colors.bold(`http://${host}:${actualPort}/`))}`);
      logger.server(`Developer Dashboard active at: ${colors.brightCyan(colors.bold(`http://${host}:${actualPort}/__zeropack`))}`);
      logger.server(`HMR WebSocket endpoint active at: ${colors.cyan(colors.bold(`ws://${host}:${actualPort}/__zeropack_hmr`))}`);
      logger.info(`Watching directory: ${colors.gray(watchDir)}`);
      resolve({ server, broadcast, close: closeServer });
    });

    server.on('error', (err) => {
      if (err.code === 'EADDRINUSE') {
        logger.error(`Port ${port} is already in use. Please specify another port with --port`);
      } else {
        logger.error(`Dev server error: ${err.message}`);
      }
      reject(err);
    });
  });
}
// -----------------------------------------------------------------------------
// Auto-Run CLI when invoked directly
// -----------------------------------------------------------------------------
runCli().catch((err) => {
  logger.error('Fatal CLI Error: ' + err.message);
  process.exit(1);
});
